### ISSUE TITLE
db mirror server 10.155.59.88 not synced since Dec 7th?

### ISSUE THREAD

**Issue by flotum** [nEDM-TUM/nEDM-Interface#47]
the mirror server seems to be synced only till Dec 7th. probably the date it went down for the first time?
you can check monitoring pages and also the measurements  calendar

**Comment by mgmarino** [comment]
@stefan789, try a `restart` of the db there, it will restart the corresponding replication processes:

```python
import cloudant

acct = cloudant.Account(uri="http://10.155.59.88:5984")
res = acct.login(un, pw) 
print acct.post("_restart").json()
```

**Comment by stefan789** [comment]
replication began after couchdb `restart`

closed
